[package]
name = "stm32-metapac-gen"
version = "0.1.0"
edition = "2018"


[dependencies]
regex = "1.4.6"
chiptool = { git = "https://github.com/embassy-rs/chiptool", rev = "e0c5ff926ecd86e390bd9bc68b414bfc0e811b0e" }
serde = { version = "1.0.123", features = [ "derive" ]}
serde_yaml = "0.8.15"
syn = { version = "1.0", features = ["full","extra-traits"] }
